openapi: 3.0.0
paths:
  /getActivated:
    get:
      operationId: 'controllers\ActivatedPaypalController::getActivated'
      responses:
        '200':
          description: 'get the activated paypal business account'
          content:
            application/json:
              schema: {  }
