version:  '3'
services:

  ##
  # user service
  ##
  microservice_user_fpm:
    build: ./microservices/user/php-fpm/
    volumes:
      - ../source/user:/var/www/html
    expose:
      - 9000

  microservice_user_nginx:
    build: ./microservices/user/nginx/
    volumes:
      - ../source/user:/var/www/html
    ports:
      - 8081:80
      - 9091:9090

  microservice_user_database:
    build: ./microservices/user/database/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
      - MYSQL_DATABASE=users
      - MYSQL_USER=secret
      - MYSQL_PASSWORD=mysecret
    ports:
      - 6667:3306

  ##
  # payment service
  ##
  microservice_payment_fpm:
    build: ./microservices/payment/php-fpm/
    volumes:
      - ../source/payment:/var/www/html
    expose:
      - 9000

  microservice_payment_nginx:
    build: ./microservices/payment/nginx/
    volumes:
      - ../source/payment:/var/www/html
    ports:
      - 8086:80
      - 9096:9090

  microservice_payment_database:
    build: ./microservices/payment/database/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=payment
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456789
    ports:
      - 6672:3306
